config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do 
    resources :reviews
  end

  resources :reviews do
    resources :endorsements
  end
  root 'restaurants#index'

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many  :reviews,     dependent: :destroy
	validates :name,        length: {minimum:3}, uniqueness: true
	validates :description, length: {minimum:1}
	validates :cuisine,     length: {minimum:1}   

	# Paperclip

has_attached_file :image,
                    styles: { medium: "300x300>",
                              thumb: "100x100>" },
                    default_url: "/images/:style/missing-restaurant.png",
                    storage: :s3,
                    s3_credentials: Proc.new{|a| a.instance.s3_credentials }
  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


#   has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
# :default_url => "/images/:style/missing.png",
#                     :storage => :s3,
#                     :s3_credentials => Proc.new{|a| a.instance.s3_credentials},
#                     :url =>':s3_domain_url',
#     :path => '/:class/:attachment/:id_partition/:style/:filename'

  

  def s3_credentials
    {:bucket => "byverdu-yelp", :access_key_id => Rails.application.secrets[:access_key_id], :secret_access_key => Rails.application.secrets[:secret_access_key]}
  end


  # Average rating method

	def average_rating 
		return "N/A" if reviews.none?

		reviews.inject(0){ |memo, review| memo + review.rating } / reviews.length
		#reviews.average(:rating)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
	has_many   :endorsements 
  validates  :thoughts, length: {minimum: 1}
  validates  :rating,   inclusion: (1..5)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :reviews, dependent: :destroy

  validates :username, presence:true, uniqueness: { case_sentive: false }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => [:username]


   attr_accessor :login

    def self.find_for_database_authentication(warden_conditions) # Change login from email to username
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

	def create
		@review = Review.find(params[:review_id])
		@review.endorsements.create
		render json:{ new_endorsement_count: @review.endorsements.count}
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(params[:restaurant].permit(:name,:cuisine,:description,:image))

		if @restaurant.save
			redirect_to restaurants_path

		else
			render 'new'
		end
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@restaurant.update(params[:restaurant].permit(:name,:cuisine,:description,:image))

		redirect_to restaurants_path
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		flash[:notice] = "#{@restaurant.name} has been deleted"

		redirect_to restaurants_path
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
    if @restaurant.reviews.find_by(user_id: current_user.id).nil?
      @review = @restaurant.reviews.new
    else
      flash[:notice] = 'Sorry, you can only review a restaurant once.'
      redirect_to restaurants_path
    end
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(params[:review].permit(:rating, :thoughts))
		@review.user_id = current_user.id
		if @review.save
			redirect_to '/restaurants'
		end
	end
end



# @restaurant = Restaurant.find(params[:restaurant_id])
#     if @restaurant.reviews.find_by(user_id: current_user.id).nil?
#       @review = @restaurant.reviews.new
#     else
#       flash[:notice] = 'Sorry, you can only review a restaurant once.'
#       redirect_to restaurants_path
#     end


		# @restaurant = Restaurant.find(params[:restaurant_id])
		# @review     = Review.new

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def star_rating rating
		return rating unless rating.respond_to?(:round)

			reminder = (5 - rating.round)

			'★' * rating.round + ('☆' * reminder)
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf8">
	<link rel="shortcut icon" href="http://s3-media2.fl.yelpcdn.com/assets/2/www/img/118ff475a341/ico/favicon.ico">

  <title>Yelp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= notice %>

	<header>
		<section>
			<%= image_tag('logo.png') %>
			
			<div>
				<% if user_signed_in? %>
					
					<%= link_to 'Sign Out',     destroy_user_session_path, method: :delete  , class: 'link' %>
				  <%= link_to "Edit Account", edit_user_registration_path, class: 'link' %>
				
				<% end %>

				<% if request.fullpath != "/users/sign_up" && request.fullpath != "/users/sign_in" && !user_signed_in? %>

					<%= link_to 'Sign In',  new_user_session_path,       class: 'link' %>
				  <%= link_to 'Sign Up',  new_user_registration_path,  class: 'link' %>
				  
				 <%end%>
				  <%= link_to 'Home',  restaurants_path  ,             class: 'link' %>
			</div>
		 </section>
	</header>

	<div class="wrapper">
		<%= yield %>
	</div>
	
	<footer>
		<%= image_tag('happy_footer.png') %>
	</footer>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
	<div class="errors">
		<h2> <%= pluralize(@restaurant.errors.count,"error") %> prohibited this resraurant</h2>
		
		<ul>
			<% @restaurant.errors.full_messages.each do |message|%>
			<li><%=message%></li>
			<%end%>
		</ul>
	</div>
<%end%>

<%= form_for @restaurant, :html => { :multipart => true } do |form| %>

<%= form.label      :name                             %>
<%= form.text_field :name, placeholder: 'Name'        %>

<%= form.label      :cuisine                          %>
<%= form.text_field :cuisine, placeholder: 'Cuisine'  %>

<%= form.label      :description  %>
<%= form.text_area  :description  %>

<%= form.label      :image                %>
<%= form.file_field :image, class: 'link' %>

<%= form.submit                   %>

<% end %>

app/views/restaurants/edit.html.erb
<h2> <%= @restaurant.name %> </h2>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>

	<% @restaurants.each do | restaurant | %>
	
	<section class="resraurant">
		
		<%= image_tag restaurant.image.url(:thumb) if restaurant.image? %>

		<h1><%= restaurant.name %></h1>

		<h3> <%= restaurant.cuisine %> </h3>

		<p>  <%= restaurant.description%></p>
		
		<% if user_signed_in? %>

			<div class="link_cont">
			
			<%= link_to "Edit" , edit_restaurant_path(restaurant)              , class: 'link'    %>
			<%= link_to "Delete",  restaurant_path(restaurant), method: :delete  , class: 'link'  %>

			<%= link_to "Show",  restaurant_path(restaurant)  , class: 'link'               %>
			<%= link_to "Review",  new_restaurant_review_path(restaurant)  , class: 'link'  %>
			</div>
			<ul>
				<% restaurant.reviews.each do | review | %>
					<li> <%= "#{review.thoughts} (#{review.rating})"%> </li>
					<li class="arrenge_endorsement"> 
							<%= link_to 'Endorse this review',review_endorsements_path(review), class: "review_endorsement"  %> 
							<b class="endorsements_count"> <%= review.endorsements.count %>  </b> endorsement
					</li>
				<% end %>
			</ul>
		
		<% else %>
			<ul>
				<% restaurant.reviews.each do | review | %>
					<li> <%= "#{review.thoughts} (#{review.rating})"%> </li>
				<% end %>
			</ul>
		<% end %>

		<span> Average: <%= star_rating(restaurant.average_rating) %></span>
	
	</section>
 <% end %>

<% else %>

	<h3>There is no restaurants yet</h3>

<% end %>


<% if user_signed_in? %>

	<%= link_to 'Add Restaurant', new_restaurant_path  , class: 'link'  %>

<% else %>
	
	<h3>Only registered users can add a restaurant</h3>

<% end %>	

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<section class="show">
	<h1><%= @restaurant.name %></h1>
	<p><%= @restaurant.description %></p>
	
	<ul>
	<% @restaurant.reviews.each do | review | %>
			<li> <%= "#{review.thoughts} (#{review.rating})"%> 
			<%= link_to 'Endorse this review',review_endorsements_path(review), class: "review_endorsement"%> 

				<span class="endorsements_count"> <%= review.endorsements.count %> endorsement </span>
			</li>

	<% end %>
	</ul>
			<p> Average: <%= star_rating(@restaurant.average_rating) %></p>
		
	<%= image_tag @restaurant.image.url(:medium) %>
</section>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do | form | %>
<%= form.label     :thoughts      %>
<%= form.text_area :thoughts      %>

<%= form.label  :rating           %>
<%= form.select :rating, (0..5)   %>

<%= form.submit 'Leave Review'    %>

<% end %>